import os
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.responses import FileResponse
from pydantic import BaseModel

from parser import parse_email
from headers import analyze_authentication
from ip_extractor import analyze_received_chain, build_origin_summary
from geolocation import get_geolocation
from url_analyzer import analyze_email_urls
from evidence_engine import calculate_evidence
from risk_engine import calculate_risk
from confidence import calculate_confidence
from explainability import build_explanation

# IMPORTANT:
# Use ai_manager, NOT ai_analyzer, in main.py.
from ai_manager import analyze_email_with_ai

from case_manager import create_case
from report_generator import generate_forensic_report


# ============================================================
# APP CONFIG
# ============================================================

app = FastAPI(
    title="Threat-Trace API",
    description="Automated Email Forensics, Origin Traceability & Threat Intelligence Platform",
    version="1.0.0",
)

BASE_DIR = Path(__file__).resolve().parent

EMAILS_DIR = BASE_DIR / "emails"
ACTUAL_DIR = EMAILS_DIR / "actual"
SPAM_DIR = EMAILS_DIR / "spam"
REPORTS_DIR = BASE_DIR / "reports"

ACTUAL_DIR.mkdir(parents=True, exist_ok=True)
SPAM_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

MAX_EMAIL_SIZE = 2 * 1024 * 1024


# ============================================================
# REQUEST MODEL
# ============================================================

class EmailRequest(BaseModel):
    email: str | None = None
    raw_email: str | None = None


# ============================================================
# HELPERS
# ============================================================

def get_raw_email(request: EmailRequest) -> str:
    raw_email = request.email or request.raw_email

    if not raw_email:
        raise HTTPException(
            status_code=400,
            detail="No email content supplied."
        )

    if not raw_email.strip():
        raise HTTPException(
            status_code=400,
            detail="Email content is empty."
        )

    if len(raw_email.encode("utf-8", errors="replace")) > MAX_EMAIL_SIZE:
        raise HTTPException(
            status_code=413,
            detail="Email exceeds the 2 MB size limit."
        )

    return raw_email


def safe_filename(filename: str) -> str:
    """
    Prevent unsafe filenames from being used on disk.
    """
    filename = Path(filename).name
    filename = re.sub(r"[^a-zA-Z0-9._-]", "_", filename)

    if not filename:
        filename = "email.eml"

    return filename


def unique_email_path(directory: Path, filename: str) -> Path:
    filename = safe_filename(filename)

    path = directory / filename

    if not path.exists():
        return path

    stem = path.stem
    suffix = path.suffix

    return directory / f"{stem}_{uuid.uuid4().hex[:8]}{suffix}"


def safe_case_id(case_id: str) -> str:
    """
    Only allow the case ID format generated by case_manager.py.
    """
    pattern = r"^TT-\d{8}-[A-Fa-f0-9]{8}$"

    if not re.fullmatch(pattern, case_id):
        raise HTTPException(
            status_code=400,
            detail="Invalid case ID format."
        )

    return case_id


# ============================================================
# CORE ANALYSIS PIPELINE
# ============================================================

def analyze_raw_email(raw_email: str) -> dict:

    # --------------------------------------------------------
    # 1. Parse RFC 822 email
    # --------------------------------------------------------

    parsed_email = parse_email(raw_email)

    # --------------------------------------------------------
    # 2. SPF / DKIM / DMARC
    # --------------------------------------------------------

    auth_data = analyze_authentication(parsed_email)

    # --------------------------------------------------------
    # 3. Received header / originating IP
    # --------------------------------------------------------

    ip_data = analyze_received_chain(
        parsed_email.get("received", [])
    )

    origin_summary = build_origin_summary(ip_data)

    originating_ip = ip_data.get("originating_ip")

    # --------------------------------------------------------
    # 4. IP Geolocation
    # --------------------------------------------------------

    geo_data = get_geolocation(originating_ip)

    # --------------------------------------------------------
    # 5. URL intelligence
    # --------------------------------------------------------

    url_data = analyze_email_urls(
        parsed_email.get("body", ""),
        auth_data.get("from_domain", ""),
    )

    # --------------------------------------------------------
    # 6. Deterministic forensic evidence
    # --------------------------------------------------------

    evidence_data = calculate_evidence(
        parsed_email,
        auth_data,
        ip_data,
        url_data,
    )

    # --------------------------------------------------------
    # 7. Risk calculation
    # --------------------------------------------------------

    threat_score = evidence_data.get(
        "threat_score",
        0
    )

    risk_data = calculate_risk(threat_score)

    # --------------------------------------------------------
    # 8. Confidence
    # --------------------------------------------------------

    evidence_list = evidence_data.get(
        "evidence",
        []
    )

    confidence_data = calculate_confidence(
        threat_score,
        evidence_list,
        auth_data,
        url_data,
        ip_data,
    )

    # --------------------------------------------------------
    # 9. Explainability
    # --------------------------------------------------------

    classification = evidence_data.get(
        "classification",
        "legitimate"
    )

    explanation_data = build_explanation(
        threat_score,
        classification,
        evidence_list,
        risk_data.get("risk_level", "LOW"),
    )

    # --------------------------------------------------------
    # 10. AI ANALYSIS
    # --------------------------------------------------------

    # Send the normalized forensic information to ai_manager.
    #
    # ai_manager decides:
    #
    # Gemini
    #   ↓
    # Groq
    #   ↓
    # OpenRouter
    #   ↓
    # Ollama
    #
    # depending on your configuration.

    ai_input = {
        "from": parsed_email.get("from", ""),
        "to": parsed_email.get("to", ""),
        "subject": parsed_email.get("subject", ""),
        "date": parsed_email.get("date", ""),
        "body": parsed_email.get("body", ""),

        "received": parsed_email.get(
            "received",
            []
        ),

        "spf": auth_data.get(
            "spf",
            ""
        ),

        "dkim": auth_data.get(
            "dkim",
            ""
        ),

        "dmarc": auth_data.get(
            "dmarc",
            ""
        ),

        "originating_ip": originating_ip or "",

        "url_count": url_data.get(
            "url_count",
            0
        ),

        "suspicious_url_count": url_data.get(
            "suspicious_url_count",
            0
        ),

        "deterministic_threat_score": threat_score,

        "deterministic_classification": classification,

        "forensic_evidence": evidence_list,
    }

    try:
        ai_data = analyze_email_with_ai(ai_input)

    except Exception as error:
        # AI must NEVER crash the entire forensic API.
        ai_data = {
            "threat_score": threat_score,
            "classification": classification,
            "psychological_tactic": "",
            "forensic_summary": (
                "AI analysis failed. "
                "Deterministic forensic analysis was used."
            ),
            "indicators_of_compromise": [],
            "ai_provider": "none",
            "ai_status": "failed",
            "ai_error": str(error),
        }

    # --------------------------------------------------------
    # 11. Decide final classification
    # --------------------------------------------------------

    # Deterministic engine remains the safety net.
    #
    # If AI returns a valid result, we expose both:
    #
    # deterministic result
    # AI result
    #
    # This is useful during SIH demonstration.

    final_score = ai_data.get(
        "threat_score",
        threat_score
    )

    final_classification = ai_data.get(
        "classification",
        classification
    )

    # Ensure valid score
    try:
        final_score = int(final_score)
    except Exception:
        final_score = threat_score

    final_score = max(
        0,
        min(100, final_score)
    )

    allowed_classes = {
        "legitimate",
        "phishing",
        "bec",
        "spoofed",
    }

    if final_classification not in allowed_classes:
        final_classification = classification

    # --------------------------------------------------------
    # 12. Final risk based on AI score
    # --------------------------------------------------------

    final_risk = calculate_risk(
        final_score
    )

    # --------------------------------------------------------
    # 13. Case + evidence hashes
    # --------------------------------------------------------

    evidence_for_case = {
        "parsed_email": parsed_email,
        "authentication": auth_data,
        "origin": ip_data,
        "geolocation": geo_data,
        "urls": url_data,
        "evidence": evidence_data,
        "risk": final_risk,
        "confidence": confidence_data,
        "explanation": explanation_data,
        "ai_analysis": ai_data,
    }

    case_data = create_case(
        raw_email,
        evidence_for_case
    )

    case_id = case_data["case_id"]

    # --------------------------------------------------------
    # 14. Generate forensic PDF
    # --------------------------------------------------------

    analysis_for_report = {
        "case_id": case_id,
        "created_at": case_data.get(
            "created_at",
            datetime.now(timezone.utc).isoformat()
        ),

        "threat_score": final_score,
        "risk_level": final_risk.get(
            "risk_level",
            "LOW"
        ),

        "classification": final_classification,

        "sender": parsed_email.get(
            "from",
            ""
        ),

        "recipient": parsed_email.get(
            "to",
            ""
        ),

        "subject": parsed_email.get(
            "subject",
            ""
        ),

        "date": parsed_email.get(
            "date",
            ""
        ),

        "spf": auth_data.get(
            "spf",
            ""
        ),

        "dkim": auth_data.get(
            "dkim",
            ""
        ),

        "dmarc": auth_data.get(
            "dmarc",
            ""
        ),

        "originating_ip": originating_ip,

        "origin_confidence": ip_data.get(
            "origin_confidence",
            ""
        ),

        "country": geo_data.get(
            "country"
        ),

        "region": geo_data.get(
            "region"
        ),

        "city": geo_data.get(
            "city"
        ),

        "latitude": geo_data.get(
            "latitude"
        ),

        "longitude": geo_data.get(
            "longitude"
        ),

        "isp": geo_data.get(
            "isp"
        ),

        "url_data": url_data,

        "indicators_of_compromise": ai_data.get(
            "indicators_of_compromise",
            []
        ),

        "evidence": evidence_list,

        "explanation": explanation_data,

        "confidence": confidence_data,

        "ai_analysis": ai_data,

        "evidence_integrity": case_data.get(
            "evidence_integrity",
            {}
        ),
    }

    report_path = REPORTS_DIR / f"{case_id}.pdf"

    try:
        generate_forensic_report(
            analysis_for_report,
            str(report_path)
        )
    except Exception as error:
        # Report failure should not destroy the analysis.
        report_path = None
        report_error = str(error)
    else:
        report_error = None

    # --------------------------------------------------------
    # 15. Save original email
    # --------------------------------------------------------

    if final_classification == "legitimate":
        email_directory = ACTUAL_DIR
    else:
        email_directory = SPAM_DIR

    filename = f"{case_id}.eml"

    email_path = email_directory / filename

    try:
        email_path.write_text(
            raw_email,
            encoding="utf-8"
        )
    except Exception as error:
        email_path = None
        email_save_error = str(error)
    else:
        email_save_error = None

    # --------------------------------------------------------
    # 16. Final API response
    # --------------------------------------------------------

    response = {
        # ====================================================
        # CASE
        # ====================================================

        "case": {
            "case_id": case_id,

            "created_at": case_data.get(
                "created_at"
            ),

            "email_file": (
                str(email_path)
                if email_path
                else None
            ),

            "report_file": (
                str(report_path)
                if report_path
                else None
            ),
        },

        # ====================================================
        # FINAL RESULT
        # ====================================================

        "result": {
            "threat_score": final_score,

            "risk_level": final_risk.get(
                "risk_level"
            ),

            "classification": final_classification,

            "recommended_action": final_risk.get(
                "recommended_action"
            ),
        },

        # ====================================================
        # EMAIL
        # ====================================================

        "email": {
            "from": parsed_email.get(
                "from",
                ""
            ),

            "to": parsed_email.get(
                "to",
                ""
            ),

            "subject": parsed_email.get(
                "subject",
                ""
            ),

            "date": parsed_email.get(
                "date",
                ""
            ),
        },

        # ====================================================
        # AUTHENTICATION
        # ====================================================

        "authentication": {
            "spf": auth_data.get(
                "spf",
                "unknown"
            ),

            "dkim": auth_data.get(
                "dkim",
                "unknown"
            ),

            "dmarc": auth_data.get(
                "dmarc",
                "unknown"
            ),

            "risk": auth_data.get(
                "authentication_risk",
                0
            ),

            "findings": auth_data.get(
                "findings",
                []
            ),
        },

        # ====================================================
        # ORIGIN
        # ====================================================

        "origin": {
            "originating_ip": originating_ip,

            "confidence": ip_data.get(
                "origin_confidence"
            ),

            "method": ip_data.get(
                "origin_method"
            ),

            "header_count": ip_data.get(
                "header_count",
                0
            ),

            "public_ip_count": len(
                ip_data.get(
                    "public_ips",
                    []
                )
            ),

            "summary": origin_summary,
        },

        # ====================================================
        # GEOLOCATION
        # ====================================================

        "geolocation": geo_data,

        # ====================================================
        # URL INTELLIGENCE
        # ====================================================

        "url_intelligence": url_data,

        # ====================================================
        # DETERMINISTIC FORENSICS
        # ====================================================

        "forensics": {
            "threat_score": threat_score,

            "classification": classification,

            "evidence": evidence_list,

            "evidence_details": evidence_data.get(
                "evidence_details",
                []
            ),

            "risk_breakdown": evidence_data.get(
                "risk_breakdown",
                {}
            ),

            "details": evidence_data.get(
                "details",
                {}
            ),
        },

        # ====================================================
        # CONFIDENCE
        # ====================================================

        "confidence": confidence_data,

        # ====================================================
        # EXPLAINABILITY
        # ====================================================

        "explanation": explanation_data,

        # ====================================================
        # AI
        # ====================================================

        "ai_analysis": ai_data,

        # ====================================================
        # INTEGRITY
        # ====================================================

        "evidence_integrity": case_data.get(
            "evidence_integrity",
            {}
        ),

        # ====================================================
        # ERRORS / WARNINGS
        # ====================================================

        "warnings": {
            "report_error": report_error,

            "email_save_error": email_save_error,
        },
    }

    return response


# ============================================================
# API: ANALYZE RAW EMAIL
# ============================================================

@app.post("/api/analyze")
async def analyze_email(request: EmailRequest):

    raw_email = get_raw_email(request)

    try:
        result = analyze_raw_email(
            raw_email
        )

        return result

    except HTTPException:
        raise

    except Exception as error:

        print("\n========== ANALYSIS ERROR ==========")
        print(type(error).__name__)
        print(str(error))
        print("====================================\n")

        raise HTTPException(
            status_code=500,
            detail=f"Email analysis failed: {str(error)}"
        )


# ============================================================
# API: ANALYZE .EML FILE
# ============================================================

@app.post("/api/analyze/file")
async def analyze_email_file(
    file: UploadFile = File(...)
):

    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is missing."
        )

    if not file.filename.lower().endswith(".eml"):
        raise HTTPException(
            status_code=400,
            detail="Only .eml files are supported."
        )

    content = await file.read()

    if not content:
        raise HTTPException(
            status_code=400,
            detail="Uploaded file is empty."
        )

    if len(content) > MAX_EMAIL_SIZE:
        raise HTTPException(
            status_code=413,
            detail="Email exceeds the 2 MB size limit."
        )

    try:
        raw_email = content.decode(
            "utf-8",
            errors="replace"
        )

    except Exception as error:

        raise HTTPException(
            status_code=400,
            detail=f"Unable to decode email file: {error}"
        )

    try:
        result = analyze_raw_email(
            raw_email
        )

        return result

    except Exception as error:

        print("\n========== FILE ANALYSIS ERROR ==========")
        print(type(error).__name__)
        print(str(error))
        print("=========================================\n")

        raise HTTPException(
            status_code=500,
            detail=f"Email file analysis failed: {str(error)}"
        )


# ============================================================
# API: DOWNLOAD REPORT
# ============================================================

@app.get("/api/reports/{case_id}")
async def get_report(case_id: str):

    case_id = safe_case_id(case_id)

    report_path = REPORTS_DIR / f"{case_id}.pdf"

    if not report_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Forensic report not found."
        )

    return FileResponse(
        path=str(report_path),
        media_type="application/pdf",
        filename=f"{case_id}.pdf",
    )


# ============================================================
# HEALTH
# ============================================================

@app.get("/health")
async def health():

    return {
        "status": "ok",
        "service": "Threat-Trace",
        "version": "1.0.0",
        "ai_manager": "enabled",
        "timestamp": datetime.now(
            timezone.utc
        ).isoformat(),
    }


# ============================================================
# ROOT
# ============================================================

@app.get("/")
async def root():

    return {
        "name": "Threat-Trace",
        "description": (
            "Automated Email Forensics, "
            "Origin Traceability & "
            "Threat Intelligence Platform"
        ),
        "status": "running",
        "docs": "/docs",
        "health": "/health",
    }